// <auto-generated />
namespace MVCAuto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Add_FK_dboVehicles_dboColorVehicles_ColorID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_FK_dboVehicles_dboColorVehicles_ColorID));
        
        string IMigrationMetadata.Id
        {
            get { return "202002182153040_Add_FK_dbo.Vehicles_dbo.ColorVehicles_ColorID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
